(function () {
  'use strict';

  window.MagnateTipsData = {
    categoryColors: {
      "subscriptions": "#F44336",
      "food": "#FF9800",
      "shopping-smart": "#4CAF50",
      "finance": "#f1bd41",
      "transportation": "#00BCD4",
      "housing-utilities": "#D84315",
      "health-wellness": "#C2185B",
      "entertainment": "#AA00FF"
    },

    tipsBank: {
      "subscriptions": [
        "Audit all your subscriptions monthly.",
        "Cancel unused services immediately.",
        "Share family plans with friends or family.",
        "Use free trials wisely\u2014set calendar reminders.",
        "Bundle services for discounts (phone, internet, streaming).",
        "Switch to annual billing\u2014often cheaper than monthly.",
        "Look for discounts and promotions for premium services.",
        "Choose ad-supported free versions when available.",
        "Rotate subscriptions based on your current needs.",
        "Negotiate with providers for better rates.",
        "Use cashback apps and reward points for subscription payments.",
        "Use library resources for free access to premium databases.",
        "Track subscription costs to see the total monthly impact.",
        "Set spending limits on your payment methods for subscriptions.",
        "Opt for basic plans instead of premium tiers.",
        "Use browser extensions to view content if you're tempted to subscribe.",
        "Downgrade plans during months you won't use them heavily.",
        "Cancel free trials before they charge.",
        "Combine similar services under one provider for family discounts.",
        "Review and adjust your subscriptions quarterly."
      ],
      "food": [
        "Meal prep instead of eating out.",
        "Use coupons and look for discounts.",
        "Don't grocery shop while hungry.",
        "Shop store brands\u2014they're cheaper.",
        "Cook with family or friends to split costs.",
        "Plan meals around what's on sale.",
        "Bring snacks from home to avoid convenience store purchases.",
        "Freeze leftovers for easy meals later.",
        "Drink more water\u2014it's free and healthy.",
        "Avoid delivery fees by picking up your order.",
        "Use apps like Too Good To Go for discounted meals.",
        "Skip lattes\u2014brew your own coffee.",
        "Look for community events with free food.",
        "Try \"meatless Mondays\" to cut grocery costs.",
        "Make a grocery list and stick to it.",
        "Keep snacks at home to avoid impulse buys.",
        "Avoid pre-cut produce\u2014do it yourself.",
        "Use cashback apps like Ibotta when shopping.",
        "Buy generic brands for pantry staples.",
        "Plan your meals for the week ahead."
      ],
      "shopping-smart": [
        "Wait 24 hours before making non-essential purchases.",
        "Use browser extensions for coupon codes.",
        "Buy in off-seasons for clothes and tech.",
        "Join discount programs and loyalty schemes.",
        "Never pay full price\u2014always search for a promo.",
        "Use cashback sites like Rakuten.",
        "Unsubscribe from marketing emails to resist temptation.",
        "Shop thrift stores for clothes and decor.",
        "Compare prices online before buying in-store.",
        "Budget before browsing\u2014set a limit.",
        "Don't fall for \"limited-time\" marketing tricks.",
        "Buy quality over quantity\u2014it lasts longer.",
        "Use credit cards with cashback only if you can pay them off.",
        "Delay upgrades\u2014wait until your current device breaks.",
        "Consider refurbished tech for major savings.",
        "Borrow instead of buying rarely-used items.",
        "Use price tracking tools like CamelCamelCamel.",
        "Wait for major sale events like Black Friday & Cyber Monday.",
        "Set a shopping wishlist to avoid impulse purchases.",
        "Check if you can rent or borrow tools and equipment instead of buying."
      ],
      "finance": [
        "Track every dollar\u2014use a budgeting app.",
        "Set financial goals and review monthly.",
        "Build an emergency fund\u2014start small.",
        "Avoid credit card debt\u2014pay in full monthly.",
        "Set up auto-transfer to savings every payday.",
        "Check your bank statements for subscriptions to cancel.",
        "Use a checking account with no fees.",
        "Pay off high-interest loans first.",
        "Only borrow what you need.",
        "Understand how interest accrues on your debt.",
        "Avoid payday loans\u2014explore safer alternatives.",
        "Round up purchases to build savings passively.",
        "Open a high-yield savings account.",
        "Learn basic investing early\u2014time is your ally.",
        "File your taxes on time.",
        "Get a part-time job to build experience and income.",
        "Use free financial literacy tools or workshops.",
        "Avoid buying something just because it's on sale.",
        "Protect your credit score\u2014don't miss payments.",
        "Review your budget weekly and adjust as needed."
      ],
      "transportation": [
        "Use public transit instead of rideshares.",
        "Look into discounted transit passes.",
        "Walk or bike when possible\u2014it's free and healthy.",
        "Use carpool apps to share rides and costs.",
        "Avoid peak-time fares on transit systems.",
        "Keep your tires properly inflated for better fuel efficiency.",
        "Don't speed\u2014it burns more gas.",
        "Bundle errands to cut down on trips.",
        "Download gas price comparison apps.",
        "Use cruise control on highways to save fuel.",
        "Maintain your car\u2014prevent expensive issues later.",
        "Consider car sharing instead of owning.",
        "Look for discounts on travel apps.",
        "Skip parking fees by using free lots or biking.",
        "Split gas with friends for longer trips.",
        "Plan ahead to avoid surge pricing for rideshares.",
        "Avoid idling\u2014turn off your car if you're waiting.",
        "Use reward programs for gas stations.",
        "Take advantage of shuttle services if available.",
        "Use preloaded transit cards to track and control spending."
      ],
      "housing-utilities": [
        "Split rent and utilities with roommates.",
        "Use LED bulbs\u2014they last longer and cost less.",
        "Unplug devices when not in use.",
        "Keep your thermostat a few degrees lower or higher.",
        "Don't run half-loads in dishwashers or laundry.",
        "Use natural light during the day.",
        "Run fans instead of AC when possible.",
        "Use weather stripping to keep warm or cool air in.",
        "Report maintenance issues early to avoid big repairs.",
        "Buy secondhand furniture or get it free on local boards.",
        "Avoid housing with unnecessary amenities you won't use.",
        "Consider different housing options if it's cheaper.",
        "Use smart power strips to reduce phantom energy usage.",
        "Seal air leaks around doors and windows to improve insulation.",
        "Wash clothes in cold water to save energy.",
        "Air dry laundry to save electricity.",
        "Monitor your water usage\u2014shorter showers save money.",
        "Look for housing assistance programs.",
        "Insulate your water heater to save on heating costs.",
        "Choose housing that includes utilities in rent."
      ],
      "health-wellness": [
        "Use community gym facilities when possible.",
        "Take advantage of community health clinics.",
        "Use generic medications\u2014they cost less.",
        "Don't skip preventative care\u2014it saves long-term.",
        "Learn simple home remedies for common issues.",
        "Stay hydrated\u2014water is free.",
        "Get enough sleep\u2014it reduces costly health issues.",
        "Use free meditation or fitness apps.",
        "Avoid convenience store snacks\u2014bring your own.",
        "Budget for self-care\u2014it's not a luxury.",
        "Join free fitness groups in your community.",
        "Grow your own herbs or vegetables to save on grocery costs.",
        "Quit smoking/vaping\u2014it's expensive and unhealthy.",
        "Walk regularly\u2014it's exercise and saves money.",
        "Shop around for the best prescription drug prices.",
        "Avoid energy drinks\u2014get natural rest instead.",
        "Keep a reusable water bottle on you.",
        "Use health insurance benefits like free annual checkups.",
        "Try stress relief techniques to avoid burnout.",
        "Compare prices at different pharmacies for prescriptions."
      ],
      "entertainment": [
        "Look for discounts on museum and event tickets.",
        "Host movie nights with friends instead of going out.",
        "Stream content instead of paying for cable.",
        "Attend free community events.",
        "Use music streaming services with family plans.",
        "Game during free trials or on free-to-play platforms.",
        "Explore local parks and hikes for free fun.",
        "Use the library for free books and movies.",
        "Share streaming accounts with family.",
        "Look for free concerts or open mic nights.",
        "Try board games or card games at home.",
        "Volunteer at events to get in free.",
        "Look for discounts at theaters and entertainment venues.",
        "Limit impulse purchases at the app store.",
        "Create a home library with borrowed books and magazines.",
        "Explore local community centers for free activities.",
        "Use YouTube for free classes and entertainment.",
        "Plan themed nights with potlucks.",
        "Look for deals on Groupon or local apps.",
        "Follow local social media for free/cheap events."
      ]
    }
  };
})();